version: '3.6'
services:
  plant-manager-backend:
    container_name: plant-manager-backend
    image: tomir/plant-manager-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://plant-manager-postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=plant_manager
      - SPRING_DATASOURCE_PASSWORD=plant_manager_password
      - FLYWAY_URL=jdbc:postgresql://plant-manager-postgres:5432/postgres
      - FLYWAY_USER=plant_manager
      - FLYWAY_PASSWORD=plant_manager_password
    ports:
      - '8080:8080'
    depends_on:
      - plant-manager-postgres

  plant-manager-front:
    container_name: plant-manager-front
    image: tomir/plant-manager-front
    ports:
      - '3000:3000'
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - plant-manager-backend

  plant-manager-postgres:
    ports:
      - '5432:5432'
    container_name: plant-manager-postgres
    environment:
       POSTGRES_USER: plant_manager
       POSTGRES_PASSWORD: plant_manager_password
       POSTGRES_DB: postgres
    image: postgres
