package com.PlantManager.Enums;

public enum FormationType {
    HOKIDACHI, CHOKKAN, MOYOGI, SHAKAN, KENGAI,
    HANKENGAI, BUNJINGI, FUKINAGASHI, SOKAN, KABUDACHI,
    YOSEUE, SEKIJOJU, ISHISUKI, IKADABUKI, SHARIMIKI
}
